[toolchain]

[features]
seeds = false
skip-lint = false

[programs.localnet]
luda = "H9yuw3TyrwQEFyQK242sYqhyqNWeMtT3YFT9Kx7XeH6q"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/home/evo/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
